// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBobpVpnt_0fTy-YcKqp_S8p5JEpa0CB-w',
    appId: '1:48336755054:web:72497f1e7d26645e13897f',
    messagingSenderId: '48336755054',
    projectId: 'my-iot-projects-d1d93',
    authDomain: 'my-iot-projects-d1d93.firebaseapp.com',
    databaseURL: 'https://my-iot-projects-d1d93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-iot-projects-d1d93.appspot.com',
    measurementId: 'G-FXTTJN4GTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPzhYr5F-HbRQUrKmD8f9ot6Hc1i0XJBI',
    appId: '1:48336755054:android:de1dacf9fa899c4913897f',
    messagingSenderId: '48336755054',
    projectId: 'my-iot-projects-d1d93',
    databaseURL: 'https://my-iot-projects-d1d93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-iot-projects-d1d93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmj0re77-PQ-i_eVIFxFaay2jcyEEtAns',
    appId: '1:48336755054:ios:70236afcecd7687613897f',
    messagingSenderId: '48336755054',
    projectId: 'my-iot-projects-d1d93',
    databaseURL: 'https://my-iot-projects-d1d93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-iot-projects-d1d93.appspot.com',
    iosBundleId: 'com.example.fbDht11Example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmj0re77-PQ-i_eVIFxFaay2jcyEEtAns',
    appId: '1:48336755054:ios:70236afcecd7687613897f',
    messagingSenderId: '48336755054',
    projectId: 'my-iot-projects-d1d93',
    databaseURL: 'https://my-iot-projects-d1d93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-iot-projects-d1d93.appspot.com',
    iosBundleId: 'com.example.fbDht11Example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBobpVpnt_0fTy-YcKqp_S8p5JEpa0CB-w',
    appId: '1:48336755054:web:0916016a4cb646db13897f',
    messagingSenderId: '48336755054',
    projectId: 'my-iot-projects-d1d93',
    authDomain: 'my-iot-projects-d1d93.firebaseapp.com',
    databaseURL: 'https://my-iot-projects-d1d93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-iot-projects-d1d93.appspot.com',
    measurementId: 'G-5JV0DVKYNS',
  );
}
